version: '3.9'
services:
  web:
    image: nginx:latest
    port:
      - "8080:80"
    network:
      - mynetwork
  
  sql:
    image: mysql5.7
    environment: 'MYSQL_ROOT_PASSWORD': examplepassword
    network:
      -mynetwork
  
  network:
    mynetwork:
      driver: bridge

